const listText = ` remcar ID, grupo, addcar ID, clima, time, painel,rg2 ID,anuncio, a nome da arma,vroupas 1/2,cinv,limpararea,skin,debug,fix,god id,tuning,wl id,unwl id,kick,kickall,ban,unban,item dinheiro,nc,tpcds,cds 1/4,tptome id,tpto id,tpway id,car {nome},pon,hash,ITEM,ungroup,dv,sequestro,garmas,roubar,saquear,chamar,/hud,id,cor,vehs,PagUP,cobrar,allcmds,players,uncuff,renomear,carcolor 1/2,status,tpall,uservehs,limparinv id,cargod,addmoeda,removermoeda,coinstoall,adm,money {quatia},group,ajuda,char,limpachat,pft {mensagem},resetchar,setgroup id,wall,kill,
    
`;

/* COMANDOS QUE VÃO RECEBER O BADGE "NOVO" */
const comandosNovos = [
 "remcar ID",
 "grupo",
 "addcar ID",
 "clima",
 "time",
 "painel",
 "rg2 ID",
 "anuncio",
 "a nome da arma",
 "vroupas 1/2",
 "cinv",
 "limpararea",
 "skin",
 "debug",
 "fix",
 "god id",
 "tuning",
 "wl id",
 "unwl id",
 "kick",
 "kickall",
 "ban",
 "unban",
 "item dinheiro",
 "nc",
 "tpcds",
 "cds 1/4",
 "tptome id",
 "tpto id",
 "tpway id",
 "car {nome}",
 "pon",
 "hash",
 "ITEM",
 "ungroup",
 "dv",
 "sequestro",
 "garmas",
 "roubar",
 "saquear",
 "chamar",
 "/hud",
 "id",
 "cor",
 "vehs",
 "PagUP",
 "cobrar",
 "allcmds",
 "players",
 "uncuff",
 "renomear",
 "carcolor 1/2",
 "status",
 "tpall",
 "uservehs",
 "limparinv id",
 "cargod",
 "addmoeda",
 "removermoeda",
 "coinstoall",
 "adm",
 "money {quatia}",
 "group",
 "ajuda",
 "char",
 "limpachat",
 "pft {mensagem}",
 "resetchar",
 "setgroup id",
 "wall",
 "kill"
];

const descricoes = {
1: "Remover um carro de um play",
2: "abrir painel de contratações",
3: "Adiciona um carro a um play",
4: "weather",
5: "12:00 horários",
6: "/painel id vc consegue setar o player cargos",
7: "SABER AS INF. DO CARA",
8: "fazer anuncio adm",
9: "FAZ COM QUE O ADM PEGUE ARMAS : taser",
10: "sem descrição",
11: "/cinv id para limpar inventario dos usuários",
12: "limpararea para limpa o local",
13: "{id} {nome da skin} alterar skin do personagem",
14: "mostra as cordenadas e hash dos objetos e ped",
15: "Fixa as batidas dos veiculos",
16: "Enche a vida e colete do player",
17: "Tuna o veiculo no máximo",
18: "Libera a Whitelist",
19: "Tira da whitelist",
20: "quit a pessoa do server",
21: "sem descrição",
22: "da ban no usuários",
23: "desbanir usuários",
24: "dar dinheiro",
25: "fica invisível",
26: "Teleporta para alguma coordenada",
27: "Gera a cordenada de onde vc está",
28: "Teleporta a pessoa para mim",
29: "teleportar para pessoa",
30: "teleporta para marcação no mapa",
31: "spawna de veiculos",
32: "ver id on",
33: "Pega a hash dos veiculos",
34: "/item mochia 1",
35: "[ID] GRUPO tira do grupo",
36: "dv apaga veículos",
37:"sequestrar alguém",
38:"sem descrição ",
39:"roubar alguem",
40:"saquear ",
41:"chamar ou call 190 192 mec",
42:"sem descrição",
43:"pega id dos usuários",
44:"sem descrição",
45:"sem descrição ",
46:"Bau do carro",
47:"cobrar usuários",
48:"aparece todos comandos da base",
49:"Ver quantos players online",
50:"retira as algemas",
51:"renomear o usuário",
52:"Altera a cor primaria e secundaria do veiculo",
53:"Verifica quantos players estão online de cada grupo",
54:"Puxa todos os players online para sua cordenada",
55:"ver os veiculos dos player",
56:"Limpa o inventario de alguem",
57:"Enche a vida e colete do player porém não sai do veiculos",
58:"{id} {quantia} adiciona moedas para loja vip",
59:"{id} {quantia} remove moedas da loja vip",
60:"adiciona moedas para todos na loja vip",
61:"envia notifacação com uma mensagem personalizada para todos",
62:"Spawna dinheiro",
63:"Adiciona a pessoa em algum grupo",
64:"Para responder os tickets",
65:"desbuga o personagem",
66:"remove todas mensagem do chat",
67:"manda mensagem no chat como prefeitura",
68:"reseta o personagem",
69:"abre um painel com os grupos de setagem",
70:"ativa o wall para ver informações",
71:"remover vida do usuário ",


};